title: Sergio's blog
name: "Sergio's personal blog"
author: Sergio Garrido
description: Learning notes and research.
profile_url: "http://chechgm.github.io"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
scholar:
  source: .
