title: Sergio's blog
name: "Sergio's personal blog"
author: Sergio Garrido
baseurl: "/chechgm"
description: Learning notes and research.
profile_url: "http://chechgm.github.io"

# Build settings
excerpt_separator: <!--more-->
