title: Sergio's blog
name: "Sergio's personal blog"
author: Sergio Garrido
baseurl: "/chechgm"
description: Document my learning notes.
profile_url: "http://chechgm.github.io"

# Build settings
plugins:
  - jekyll-feed
